#import "minecraft.typ": *

#let etched_vase = mc-block("etched_vase", "Etched Vase", custom: true)
#let bloomguard = mc-item("bloomguard", "Bloomguard", custom: true)
#let bloomguard_open = mc-item("bloomguard", "Bloomguard", custom: true)
#let bloomguard_seed = mc-item("bloomguard_seed", "Bloomguard Seed", custom: true)
//#let sap_bucket = item("sap_bucket", "Sap Bucket", custom: true)
#let spile = mc-block("spile", "Spile", custom: true)
#let protobean = mc-item("protobean", "Protobean", custom: true)
#let bean_pod = mc-item("bean_pod", "Bean Pod", custom: true)
#let bean = mc-item("bean", "Bean", custom: true)
#let glutted_log = mc-block("glutted_log", "Glutted Log", custom: true)
#let murky_crevice = mc-block("murky_crevice", "Murky Crevice", custom: true)
#let sour_kernel = mc-item("sour_kernel", "Sour Kernel", custom: true)
#let tangleroot = mc-item("tangleroot", "Tangleroot", custom: true)
#let rootsplit_sickle = mc-item("rootsplit_sickle", "Rootsplit Sickle", custom: true)
#let blooming_bulb = mc-item("blooming_bulb", "Blooming Bulb", custom: true)
#let bloom_bud = mc-item("bloom_bud", "Bloom Bud", custom: true)
#let azure_thistle_seeds = mc-item("azure_thistle_seeds", "Azure Thistle Seeds", custom: true)
#let azure_thistle = mc-item("azure_thistle", "Azure Thistle", custom: true)
#let scarlet_fang_root = mc-item("scarlet_fang_root", "Scarlet Fang Root", custom: true)
#let scarlet_fang = mc-item("scarlet_fang", "Scarlet Fang", custom: true)
#let wildstep_seed = mc-item("wildstep_seed", "Wildstep Seed", custom: true)
#let wildstep_pods = mc-item("wildstep_pods", "Wildstep Pods", custom: true)
#let pointerpod = mc-item("pointerpod", "Pointerpod", custom: true,auto-img: false)
#let twining_tendril = mc-item("twining_tendril", "Twining Tendril", custom: true)
#let straw_hat = mc-item("straw_hat", "Straw Hat", custom: true,auto-img: false)


#let mud = mc-block("mud", "Mud")
#let dirt = mc-block("dirt", "Dirt")
#let creaking_heart = mc-block("creaking_heart", "Creaking Heart")
#let soul_soil = mc-block("soul_soil", "Soul Soil")
#let moss_block = mc-block("moss_block", "Moss")
#let pale_oak_log = mc-block("pale_oak_log", "Pale Oak Log")
#let grass_block = mc-block("grass_block", "Grass")
#let sand = mc-block("sand", "Sand")
#let vault = mc-block("vault", "Vault")
#let crafting_table = mc-block("crafting_table", "Crafting Table")


#let bucket = mc-item("bucket", "Bucket")
#let iron_ingot = mc-item("iron_ingot", "Iron Ingot")
#let nether_brick = mc-item("nether_brick", "Nether Brick")
#let beetroot = mc-item("beetroot", "Beetroot")
#let ghast_tear = mc-item("ghast_tear", "Ghast Tear")
#let resin_clump = mc-item("resin_clump", "Resin Clump")
#let magma_cream = mc-item("magma_cream", "Magma Cream")
#let wheat_seeds = mc-item("wheat_seeds", "Wheat Seeds")
#let wheat = mc-item("wheat", "Wheat")
#let string = mc-item("string", "String")
#let eyeblossom = mc-item("eyeblossom", "Eyeblossom")
