#import "minecraft.typ": *

#let etched_vase = block("etched_vase", "Etched Vase", custom: true)
#let bloomguard = item("bloomguard", "Bloomguard", custom: true)
#let bloomguard_open = item("bloomguard_open", "Bloomguard", custom: true)
#let bloomguard_seed = item("bloomguard_seed", "Bloomguard Seed", custom: true)
#let sap_bucket = item("sap_bucket", "Sap Bucket", custom: true)
#let spile = block("spile", "Spile", custom: true)
#let protobean = item("protobean", "Protobean", custom: true)
#let bean_pod = item("bean_pod", "Bean Pod", custom: true)
#let bean = item("bean", "Bean", custom: true)
#let glutted_log = block("glutted_log", "Glutted Log", custom: true)
#let murky_crevice = block("murky_crevice", "Murky Crevice", custom: true)
#let sour_kernel = item("sour_kernel", "Sour Kernel", custom: true)
#let tangleroot_seed = item("tangleroot_seed", "Tangleroot Seed", custom: true)
#let rootsplit_sickle = item("rootsplit_sickle", "Rootsplit Sickle", custom: true)
#let blooming_bulb = item("blooming_bulb", "Blooming Bulb", custom: true)
#let bloom_bud = item("bloom_bud", "Bloom Bud", custom: true)
#let azure_thistle_seeds = item("azure_thistle_seeds", "Azure Thistle Seeds", custom: true)
#let azure_thistle = item("azure_thistle", "Azure Thistle", custom: true)
#let scarlet_fang_root = item("scarlet_fang_root", "Scarlet Fang Root", custom: true)
#let scarlet_fang = item("scarlet_fang", "Scarlet Fang", custom: true)


#let mud = block("mud", "Mud")
#let dirt = block("dirt", "Dirt")
#let creaking_heart = block("creaking_heart", "Creaking Heart")
#let soul_soil = block("soul_soil", "Soul Soil")
#let moss_block = block("moss_block", "Moss")
#let pale_oak_log = block("pale_oak_log", "Pale Oak Log")

#let bucket = item("bucket", "Bucket")
#let iron_ingot = item("iron_ingot", "Iron Ingot")
#let nether_brick = item("nether_brick", "Nether Brick")
#let beetroot = item("beetroot", "Beetroot")
#let ghast_tear = item("ghast_tear", "Ghast Tear")
#let resin_clump = item("resin_clump", "Resin Clump")
#let magma_cream = item("magma_cream", "Magma Cream")
